// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package cvm

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatTencentCloudAccessRole is an auto-generated flat version of TencentCloudAccessRole.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatTencentCloudAccessRole struct {
	RoleArn         *string `mapstructure:"role_arn" required:"false" cty:"role_arn" hcl:"role_arn"`
	SessionName     *string `mapstructure:"session_name" required:"false" cty:"session_name" hcl:"session_name"`
	SessionDuration *int    `mapstructure:"session_duration" required:"false" cty:"session_duration" hcl:"session_duration"`
}

// FlatMapstructure returns a new FlatTencentCloudAccessRole.
// FlatTencentCloudAccessRole is an auto-generated flat version of TencentCloudAccessRole.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*TencentCloudAccessRole) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatTencentCloudAccessRole)
}

// HCL2Spec returns the hcl spec of a TencentCloudAccessRole.
// This spec is used by HCL to read the fields of TencentCloudAccessRole.
// The decoded values from this spec will then be applied to a FlatTencentCloudAccessRole.
func (*FlatTencentCloudAccessRole) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"role_arn":         &hcldec.AttrSpec{Name: "role_arn", Type: cty.String, Required: false},
		"session_name":     &hcldec.AttrSpec{Name: "session_name", Type: cty.String, Required: false},
		"session_duration": &hcldec.AttrSpec{Name: "session_duration", Type: cty.Number, Required: false},
	}
	return s
}
