variable "secret_id" {
  type    = string
  default = "${env("TENCENTCLOUD_SECRET_ID")}"
}

variable "secret_key" {
  type    = string
  default = "${env("TENCENTCLOUD_SECRET_KEY")}"
}

variable "cvm_endpoint" {
  type    = string
}
variable "vpc_endpoint" {
  type    = string
}

source "tencentcloud-cvm" "autogenerated_1" {
  associate_public_ip_address = true
  disk_type                   = "CLOUD_PREMIUM"
  image_name                  = "PackerTest"
  instance_type               = "S3.SMALL1"
  packer_debug                = true
  region                      = "chongqing"
  secret_id       = "${var.secret_id}"
  secret_key      = "${var.secret_key}"
  cvm_endpoint    = "${var.cvm_endpoint}"
  vpc_endpoint    = "${var.vpc_endpoint}"
  source_image_id = "img-95xgn7er"
  ssh_username    = "root"
  zone            = "yfm18"
}

build {
  sources = ["source.tencentcloud-cvm.autogenerated_1"]

  provisioner "shell" {
    inline = ["sleep 30"]
  }
}